# Container name
container = "swiftsftp"

# Create container if not exist
create_container = true

# Bind address
bind_address = "127.0.0.1:10022"

# File name of server key
server_key = "/etc/swift-sftp/server.key"

# File name of authorized keys
authorized_keys = "/etc/swift-sftp/authorized_keys"

# File name of password list.
# if blank, The password authentication methods will be disabled.
password_file = ""

# OpenStack configurations
os_identity_endpoint = ""
os_user_id           = ""
os_username          = ""
os_password          = ""
os_domain_id         = ""
os_domain_name       = ""
os_tenant_id         = ""
os_tenant_name       = ""
os_region            = ""
